# lame -m m --abr 32 try_3.wav clock.mp3

.PHONY: all
all: cardinal_0.wav \
	cardinal_1.wav cardinal_2.wav cardinal_3.wav \
	cardinal_4.wav cardinal_5.wav cardinal_6.wav \
	cardinal_7.wav cardinal_8.wav cardinal_9.wav \
	cardinal_10.wav \
	cardinal_11.wav cardinal_12.wav cardinal_13.wav \
	cardinal_14.wav cardinal_15.wav cardinal_16.wav \
	cardinal_17.wav cardinal_18.wav cardinal_19.wav \
	cardinal_20.wav \
	cardinal_30.wav \
	cardinal_40.wav \
	cardinal_50.wav \
	ordinal_1.wav ordinal_2.wav ordinal_3.wav \
	ordinal_4.wav ordinal_5.wav ordinal_6.wav \
	ordinal_7.wav ordinal_8.wav ordinal_9.wav \
	ordinal_10.wav \
	ordinal_11.wav ordinal_12.wav ordinal_13.wav \
	ordinal_14.wav ordinal_15.wav ordinal_16.wav \
	ordinal_17.wav ordinal_18.wav ordinal_19.wav \
	ordinal_20.wav \
	hour.wav hours.wav minute1.wav minute2.wav minutes.wav

cardinal_0.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:01.1 -t 00:00:00.9 $@

cardinal_1.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:02.4 -t 00:00:00.9 $@

cardinal_2.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:03.5 -t 00:00:00.6 $@

cardinal_3.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:04.5 -t 00:00:00.5 $@

cardinal_4.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:05.8 -t 00:00:00.7 $@

cardinal_5.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:07.0 -t 00:00:00.6 $@

cardinal_6.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:08.2 -t 00:00:00.7 $@

cardinal_7.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:09.5 -t 00:00:00.5 $@

cardinal_8.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:10.7 -t 00:00:00.8 $@

cardinal_9.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:11.8 -t 00:00:00.8 $@

cardinal_10.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:12.9 -t 00:00:00.8 $@

cardinal_11.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:14.2 -t 00:00:00.9 $@

cardinal_12.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:15.7 -t 00:00:00.9 $@

cardinal_13.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:17.1 -t 00:00:01.1 $@

cardinal_14.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:18.5 -t 00:00:01.3 $@

cardinal_15.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:20.9 -t 00:00:01.1 $@

cardinal_16.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:22.2 -t 00:00:01.1 $@

cardinal_17.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:23.4 -t 00:00:01.1 $@

cardinal_18.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:24.6 -t 00:00:01.1 $@

cardinal_19.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:25.7 -t 00:00:01.1 $@

cardinal_20.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:27.2 -t 00:00:00.7 $@

cardinal_30.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:28.3 -t 00:00:00.7 $@

cardinal_40.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:29.4 -t 00:00:00.7 $@

cardinal_50.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:30.4 -t 00:00:00.9 $@

ordinal_1.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:32.4 -t 00:00:00.6 $@

ordinal_2.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:33.4 -t 00:00:00.6 $@

ordinal_3.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:34.4 -t 00:00:00.6 $@

ordinal_4.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:35.2 -t 00:00:00.9 $@

ordinal_5.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:36.4 -t 00:00:00.6 $@

ordinal_6.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:37.3 -t 00:00:00.7 $@

ordinal_7.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:38.3 -t 00:00:00.7 $@

ordinal_8.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:39.4 -t 00:00:00.6 $@

ordinal_9.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:40.3 -t 00:00:00.9 $@

ordinal_10.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:41.4 -t 00:00:00.8 $@

ordinal_11.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:42.6 -t 00:00:00.9 $@

ordinal_12.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:43.8 -t 00:00:00.9 $@

ordinal_13.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:45.2 -t 00:00:00.9 $@

ordinal_14.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:46.5 -t 00:00:01.0 $@

ordinal_15.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:47.7 -t 00:00:01.0 $@

ordinal_16.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:48.9 -t 00:00:01.1 $@

ordinal_17.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:50.2 -t 00:00:01.0 $@

ordinal_18.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:51.5 -t 00:00:01.1 $@

ordinal_19.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:52.8 -t 00:00:01.1 $@

ordinal_20.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:54.3 -t 00:00:00.8 $@

hour.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:56.8 -t 00:00:00.6 $@

hours.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:58.0 -t 00:00:00.6 $@

minute1.wav: clock.mp3
	ffmpeg -i $< -ss 00:00:59.1 -t 00:00:00.7 $@

minute2.wav: clock.mp3
	ffmpeg -i $< -ss 00:01:00.6 -t 00:00:00.6 $@

minutes.wav: clock.mp3
	ffmpeg -i $< -ss 00:01:01.9 -t 00:00:00.6 $@
